"""Index selected editor appearances from a serialized character creator and .apps.

The catalog is metadata only. Each selected appearance retains the game's
internal option, resource, component and material names; it embeds no assets.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def creator_resources(creator: dict) -> dict[str, str]:
    root = creator["Data"]["RootChunk"]
    result = {}
    for group in ("headCustomizationOptions", "bodyCustomizationOptions", "armsCustomizationOptions"):
        for handle in root[group]:
            option = handle["Data"]
            name = option.get("name", {}).get("$value")
            resource = option.get("resource", {}).get("DepotPath", {}).get("$value")
            if isinstance(name, str) and isinstance(resource, str) and resource.lower().endswith(".app"):
                result[name] = resource
    return result


def selected_components(app: dict, name: str) -> list[dict] | None:
    for handle in app["Data"]["RootChunk"]["appearances"]:
        definition = handle["Data"]
        if definition.get("name", {}).get("$value") != name:
            continue
        components = []
        for raw in definition["components"]:
            item = raw.get("Data", raw)
            components.append({
                "name": item.get("name", {}).get("$value"),
                "kind": item.get("$type"),
                "mesh_appearance": item.get("meshAppearance", {}).get("$value"),
                "chunk_mask": item.get("chunkMask"),
                "mesh": item.get("mesh", {}).get("DepotPath", {}).get("$value"),
                "morph_resource": item.get("morphResource", {}).get("DepotPath", {}).get("$value"),
            })
        return components
    return None


def hair_mesh_variant(app: dict, selected_name: str, roots: list[Path]) -> list[dict] | None:
    """Resolve a CCXL color from installed mesh metadata, never by guessing.

    Some custom hair .apps contain one base appearance while the editor exposes
    numbered color choices generated by an .inkcharcustomization resource.
    The prefix is UI ordering; the mesh material uses the suffix.
    """
    appearances = app["Data"]["RootChunk"]["appearances"]
    if len(appearances) != 1:
        return None
    match = re.fullmatch(r"\d{1,3}_([A-Za-z0-9_]+)", selected_name)
    if not match:
        return None
    color = match.group(1)
    base = selected_components(app, appearances[0]["Data"]["name"]["$value"])
    if not base:
        return None
    meshes = [part for part in base if part["kind"] == "entSkinnedMeshComponent"]
    if any(not isinstance(part["mesh"], str) or not part["mesh"].lower().endswith(".mesh")
           for part in meshes):
        return None  # Never silently omit a hair part whose hash is unknown.
    if not meshes or not all("hair" in (part["name"] or "").lower()
                               or "hair" in part["mesh"].lower() for part in meshes):
        return None
    for part in meshes:
        path = part["mesh"].replace("/", "\\")
        segments = path.split("\\")
        if any(segment in ("", ".", "..") or ":" in segment for segment in segments):
            return None
        files = [Path(str(root.joinpath(*segments)) + ".json") for root in roots]
        file = next((candidate for candidate in files if candidate.is_file()), None)
        if file is None:
            return None
        mesh = json.loads(file.read_text(encoding="utf-8-sig"))
        names = {item["Data"]["name"]["$value"]
                 for item in mesh["Data"]["RootChunk"]["appearances"]}
        if color not in names:
            return None
        part["mesh_appearance"] = color
    return base


def build_catalog(project: dict, creator: dict, app_root: Path,
                  extra_roots: list[Path] | None = None,
                  material_sources: dict[str, str] | None = None) -> dict:
    resources = creator_resources(creator)
    choices, unresolved = {}, {}
    for option in project["options"]:
        if not (option["active"] and option["editable"] and option["kind"] == "appearance"):
            continue
        name = option["name"]
        value = option["selected_name"]
        # Skin is a shared player material without a per-choice .app.
        if name == "skin_color":
            continue
        if value in ("", "None"):
            continue
        resource = option.get("resource_path") or resources.get(name)
        if resource is None:
            unresolved[name] = "No .app resource in character creator"
            continue
        if not isinstance(resource, str) or not resource.lower().endswith(".app"):
            unresolved[name] = f"Invalid captured resource path: {resource!r}"
            continue
        resource = resource.replace("/", "\\")
        parts = resource.split("\\")
        if any(part in ("", ".", "..") or ":" in part for part in parts):
            unresolved[name] = f"Unsafe captured resource path: {resource!r}"
            continue
        roots = [*(extra_roots or []), app_root]
        files = [Path(str(root.joinpath(*resource.split("\\"))) + ".json") for root in roots]
        file = next((candidate for candidate in files if candidate.is_file()), None)
        if file is None:
            unresolved[name] = f"Missing serialized {resource}"
            continue
        app = json.loads(file.read_text(encoding="utf-8-sig"))
        components = selected_components(app, value)
        material_source = None
        if components is None and re.fullmatch(r"eyes_color|eyelash_color|eyebrows_color\d+", name):
            original = (material_sources or {}).get(resource)
            # Only the installed framework's explicit redirect permits this
            # legacy material lookup. Keep the captured runtime path in output.
            if original:
                parts = original.replace("/", "\\").split("\\")
                if any(part in ("", ".", "..") or ":" in part for part in parts):
                    raise ValueError("Unsafe ArchiveXL material source")
                sources = [Path(str(root.joinpath(*parts)) + ".json") for root in roots]
                source = next((candidate for candidate in sources if candidate.is_file()), None)
                if source:
                    legacy = json.loads(source.read_text(encoding="utf-8-sig"))
                    components = selected_components(legacy, value)
                    if components is not None:
                        material_source = original
        if components is None and "hair" in name.lower():
            components = hair_mesh_variant(app, value, roots)
        if components is None:
            unresolved[name] = f"Appearance {value!r} absent from {resource} or its hair meshes"
            continue
        choices[name] = {"selected_name": value, "source_app": resource,
                         "components": components}
        if material_source:
            choices[name]["material_metadata_source"] = material_source
    return {"format": "npv-maker-appearance-catalog", "schema_version": 1,
            "choices": choices, "unresolved": unresolved}


def require_captured_choices(project: dict, catalog: dict) -> None:
    """Never substitute a vanilla choice for a captured mod appearance."""
    missing = []
    for option in project["options"]:
        if not (option["active"] and option["editable"]
                and option["kind"] == "appearance"
                and option.get("resource_path")
                and option["name"] != "skin_color"
                and option["selected_name"] not in ("", "None")):
            continue
        if option["name"] not in catalog["choices"]:
            reason = catalog["unresolved"].get(option["name"], "Unknown source")
            missing.append(f"{option['name']}: {reason}")
    if missing:
        raise ValueError("Captured appearance cannot be resolved: " + "; ".join(missing))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project", type=Path)
    parser.add_argument("--creator", type=Path, required=True)
    parser.add_argument("--app-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        if args.output.exists():
            raise FileExistsError(args.output)
        project = json.loads(args.project.read_text(encoding="utf-8-sig"))
        creator = json.loads(args.creator.read_text(encoding="utf-8-sig"))
        catalog = build_catalog(project, creator, args.app_root)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf8")
        print(f"{args.output} ({len(catalog['choices'])} choices, {len(catalog['unresolved'])} unresolved)")
    except (OSError, ValueError, KeyError, json.JSONDecodeError) as exc:
        parser.exit(1, f"Appearance catalog failed: {exc}\n")


if __name__ == "__main__":
    main()
