"""Install only files generated by this mod after an explicit in-game request."""
from __future__ import annotations
import hashlib
import json
import os
import re
import shutil
import time
from pathlib import Path
import adapters
from companion_expansion import bridge_yaml, resource_path
from ingame_companion_worker import write_panel_file
from runtime_resources import path_hash


def runtime_bridge(record: str, digest: str) -> str:
    # Resolve the optional companion system at runtime. Leaving a generated
    # character installed must not prevent boot if Companion is later removed.
    return f'''public class NPVMakerCompanion_{digest[:16]}_BridgeSystem extends ScriptableSystem {{
  private func OnAttach() -> Void {{
    GameInstance.GetCallbackSystem()
      .RegisterCallback(n"Session/Ready", this, n"OnNPVMakerCompanionReady")
      .SetLifetime(CallbackLifetime.Forever);
  }}
  private cb func OnNPVMakerCompanionReady(event: ref<GameSessionEvent>) -> Void {{
    if GameInstance.GetSystemRequestsHandler().IsPreGame() {{ return; }};
    let reg = GameInstance.GetScriptableSystemsContainer(this.GetGameInstance()).Get(n"AikoNPVRegistrySystem");
    if IsDefined(reg) {{
      let args: array<Variant>;
      ArrayPush(args, ToVariant(n"CompanionFramework.{record}"));
      ArrayPush(args, ToVariant("NPV Maker import"));
      Reflection.Call(reg, n"UnlockCompanion", args);
    }};
  }}
}}
'''


def companion_available(game: Path) -> bool:
    return any("public class AikoNPVRegistrySystem" in p.read_text(encoding="utf-8-sig", errors="replace")
               for p in (game / "r6/scripts").rglob("AikoNPVFramework.reds"))


MORPH_NAME = re.compile(r"[A-Za-z0-9_]{1,80}")


def morph_flat(manifest: dict, entity: str) -> str:
    """TweakXL flat with the preset shapes NPV Maker applies in game (BUGS 67c, NPVMakerMorphs.reds).

    Keyed by the hash of the entity file, which the game script gets from the spawned NPC
    (Codeware ResRef.GetHash); Night City Allies spawns a copy of the record, so the record cannot
    be the key. Pairs are target, region, as Entity.ApplyMorphTarget takes them."""
    pairs = [pair for pair in manifest.get("runtime_morphs") or []
             if len(pair) == 2 and all(isinstance(v, str) and MORPH_NAME.fullmatch(v) for v in pair)]
    if not pairs:
        return ""
    values = ", ".join('n"' + value + '"' for pair in pairs for value in pair)
    return "NPVMaker.morphs_" + path_hash(entity) + ": [ " + values + " ]\n"


def checked_identity(manifest: dict) -> tuple[str, str, str]:
    """(digest, record, entity) of a locally generated NPV, refused when they do not match."""
    digest = manifest.get("project_sha256", "")
    if not re.fullmatch(r"[0-9a-f]{64}", digest):
        raise ValueError("Invalid project identity")
    if manifest.get("format") != "npv-maker-runtime-npc" or not manifest.get("local_use_only"):
        raise ValueError("Not a locally generated character")
    record = "Character.NPVMaker_" + digest[:16]
    entity = resource_path(manifest["entity_path"], ".ent")
    if manifest["record_id"] != record or not entity.startswith("npvmaker\\generated\\" + digest[:16] + "\\"):
        raise ValueError("Character namespace does not match saved project")
    return digest, record, entity


def npv_files(manifest: dict, chosen: dict, extra: dict | None = None) -> dict:
    """Every file of one NPV, by game-relative path: what INSTALAR writes and what EXPORTAR ships."""
    digest, record, entity = checked_identity(manifest)
    token = digest[:16]
    content = {
        f"archive/pc/mod/npvmaker_{token}.archive": Path(manifest["archive"]).read_bytes(),
        f"r6/tweaks/NPVMaker/generated_{token}.yaml": (bridge_yaml(
            manifest, record, manifest["base_record"], entity, manifest["appearance_name"],
            manifest.get("name_key"), companion=chosen["companion"]) + morph_flat(manifest, entity)).encode("utf8"),
    }
    if chosen["companion"]:
        content[f"r6/scripts/NPVMakerCompanion/generated_{token}.reds"] = runtime_bridge(record, digest).encode("utf8")
    for relative, text in adapters.files(chosen, token, record, entity, manifest["appearance_name"],
                                         (extra or {}).get("display_name") or manifest["name"],
                                         (extra or {}).get("author") or "",
                                         (extra or {}).get("character_id") or (extra or {}).get("local_id")
                                         or "", manifest.get("photomode"), manifest.get("name_key") or "",
                                         manifest.get("body") or "female").items():
        content[relative] = text.encode("utf8")
    # BUGS 82 (05/10/2026): the photo mode puppet is its own entity (photomode.ent), so it gets the same shape list
    # under its own key; without it the puppet of PhotoMode-EX kept the base shape of the mod pieces.
    photo = (manifest.get("photomode") or {}).get("entity")
    photo_record = f"r6/tweaks/NPVMaker/generated_{token}_photomode.yaml"
    if photo and photo_record in content:
        content[photo_record] += morph_flat(manifest, resource_path(photo, ".ent")).encode("utf8")
    if manifest.get("archive_xl"):
        # ArchiveXL patches that mods apply to meshes this NPC copies (see
        # runtime_npc.inherit_patches); ArchiveXL reads .xl beside archives.
        content[f"archive/pc/mod/npvmaker_{token}.archive.xl"] = manifest["archive_xl"].encode("utf8")
    return content


def install(game: Path, manifest: dict, require_companion: bool = True, extra: dict | None = None,
            integrations: dict | None = None) -> dict:
    """`require_companion=False` is the NPV package path: an NPV is installed without any
    consumer (author decision 30/09/2026). `integrations` (adapters.py) are the mods the package
    author marked; None is the local IMPORTAR NO COMPANION and old packages (Companion only).
    `extra` goes to the receipt only (package character_id and version)."""
    chosen = adapters.clean(integrations)
    digest, record, _ = checked_identity(manifest)
    if require_companion and not companion_available(game):
        raise ValueError("Ative o Companion Expansion e reinicie o jogo antes de importar.")
    content = npv_files(manifest, chosen, extra)
    # Preflight every destination before changing anything. Foreign/edited
    # files are never overwritten, including files deployed by Vortex.
    resolved = game.resolve()
    targets = {}
    for relative, data in content.items():
        target = game / relative
        if not target.resolve().is_relative_to(resolved):
            raise ValueError("Generated import escaped the game directory")
        if target.exists() and target.read_bytes() != data:
            raise ValueError("Arquivo de outro pacote ocupa o destino: " + relative)
        targets[relative] = target
    staged, installed = [], []
    try:
        for relative, target in targets.items():
            if target.exists():
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            temporary = target.with_suffix(target.suffix + ".npv-pending")
            # Only the single runtime owns these temporary files under its lock.
            with temporary.open("wb") as stream:
                stream.write(content[relative])
                stream.flush()
                os.fsync(stream.fileno())
            staged.append((temporary, target))
        for temporary, target in staged:
            temporary.rename(target)  # Windows refuses an existing destination.
            installed.append(target)
    except Exception:
        for target in reversed(installed):
            target.unlink(missing_ok=True)
        raise
    finally:
        for temporary, _ in staged:
            temporary.unlink(missing_ok=True)
    result = {"record_id": record, "name": manifest["name"], "project_sha256": digest,
              "restart_required": True, "integrations": chosen,
              "files": {r: hashlib.sha256(b).hexdigest() for r, b in content.items()}}
    result.update(extra or {})
    return result


# Removal of imported characters. The player creates a new NPV per test and
# never re-imports, so imported ones pile up outside Vortex; each import is
# listed in data/imports/<sha256>.json with the hash of every file it wrote.
TOKEN = re.compile(r"[0-9a-f]{16}")
# Record and bridge first: once they are gone the NPV no longer loads, even if
# the game still holds the .archive open.
REMOVAL_ORDER = (".yaml", ".reds", ".xl", ".archive")


def removal_key(relative: str) -> int:
    return next((i for i, suffix in enumerate(REMOVAL_ORDER) if relative.endswith(suffix)), len(REMOVAL_ORDER))


def receipts(plugin: Path) -> list[Path]:
    folder = plugin / "data/imports"
    return sorted(folder.glob("*.json")) if folder.is_dir() else []


def imported_index(plugin: Path) -> list[dict]:
    """What the CET window lists: no local paths, only name and identity."""
    listing = []
    for receipt in receipts(plugin):
        try:
            data = json.loads(receipt.read_text(encoding="utf8"))
        except (OSError, ValueError):
            continue
        digest = data.get("project_sha256", receipt.stem)
        listing.append({"token": digest[:16], "name": data.get("name", ""), "record_id": data.get("record_id", ""),
                        "imported_at": int(receipt.stat().st_mtime),
                        "removal_pending": sorted(data.get("removal_pending") or []),
                        "package": data.get("character_id") or "",
                        "package_version": data.get("package_version") or "",
                        # What CRIAR NPV chose; EXPORTAR starts from it. Receipts before 01/10/2026: Companion.
                        "integrations": adapters.clean(data.get("integrations")),
                        "underwear": data.get("underwear") or ""})
    return sorted(listing, key=lambda item: item["imported_at"], reverse=True)


def publish_index(plugin: Path, projects: Path) -> None:
    # The panel reads this list every second (item 35: never let a busy file stop the converter).
    write_panel_file(projects / "exports/imported.json",
                     json.dumps({"format": "npv-maker-imported", "schema_version": 1,
                                 "characters": imported_index(plugin)}, ensure_ascii=False, indent=2))


def remove_imported(game: Path, plugin: Path, token: str) -> dict:
    """Delete only files this mod wrote for one NPV, verified by hash.

    Returns removed/pending/kept lists. A file changed since the import is
    kept (never delete what we did not write); a file the running game holds
    open stays pending and is retried when the converter starts again.
    """
    if not TOKEN.fullmatch(token or ""):
        raise ValueError("Identificador de NPV invalido")
    match = [r for r in receipts(plugin) if r.stem.startswith(token)]
    if len(match) != 1:
        raise LookupError("NPV importado nao encontrado: " + token)
    receipt = match[0]
    data = json.loads(receipt.read_text(encoding="utf8"))
    digest = data.get("project_sha256", receipt.stem)
    files = data.get("files") or {}
    wanted = data.get("removal_pending") or list(files)
    resolved = game.resolve()
    removed, pending, kept = [], [], []
    for relative in sorted(wanted, key=removal_key):
        target = game / relative
        if not target.resolve().is_relative_to(resolved):
            raise ValueError("Arquivo do recibo fora da pasta do jogo: " + relative)
        if not target.exists():
            removed.append(relative)
            continue
        if hashlib.sha256(target.read_bytes()).hexdigest() != files.get(relative):
            kept.append(relative)
            continue
        try:
            target.unlink()
            removed.append(relative)
        except OSError:
            pending.append(relative)
    (plugin / "data/ready" / (digest + ".json")).unlink(missing_ok=True)
    for job in (plugin / "data/jobs").glob(digest[:16] + "-*") if (plugin / "data/jobs").is_dir() else []:
        shutil.rmtree(job, ignore_errors=True)
    if pending:
        data["removal_pending"] = pending
        receipt.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf8")
    else:
        history = plugin / "data/removed"
        history.mkdir(parents=True, exist_ok=True)
        data.pop("removal_pending", None)
        data["removed_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        data["kept_files"] = kept
        (history / receipt.name).write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf8")
        receipt.unlink()
    return {"token": digest[:16], "name": data.get("name", ""), "record_id": data.get("record_id", ""),
            "removed": removed, "pending": pending, "kept": kept}


def retry_pending_removals(game: Path, plugin: Path) -> list[dict]:
    results = []
    for receipt in receipts(plugin):
        try:
            data = json.loads(receipt.read_text(encoding="utf8"))
        except (OSError, ValueError):
            continue
        if data.get("removal_pending"):
            results.append(remove_imported(game, plugin, data.get("project_sha256", receipt.stem)[:16]))
    return results
